// Sync DNA model-portfolio parameters from the source spreadsheet into models/dnaModels.ts.
//
// Reads the "Model Portfolios" sheet of the workbook in data/ and regenerates the typed
// model list the simulator imports. Run whenever the spreadsheet changes:
//
//     npm run sync-models
//
// To point at a different workbook:  node scripts/sync-models.mjs "path/to/file.xlsx"

import XLSX from "xlsx";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Inflation assumption used to convert the spreadsheet's real (CPI+) targets to the
// nominal expected return the simulator needs. Change here and re-run to re-link.
const INFLATION_ASSUMPTION = 5.0;

const xlsxPath = process.argv[2]
  || join(ROOT, "data", "DNA_Model_Portfolio_Metrics_130726.xlsx");
const outPath = join(ROOT, "models", "dnaModels.ts");

// Model Portfolios sheet layout (header row 7, data rows 8-13):
//   B risk category | C model name | ... | Q TER | R CPI+ target | S volatility | T vol period
const FIRST_ROW = 8;
const LAST_ROW = 13;

const round1 = (n) => Math.round(n * 10) / 10;
const round2 = (n) => Math.round(n * 100) / 100;

function slug(name) {
  return name
    .replace(/DNA/gi, "")
    .replace(/Portfolio/gi, "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const wb = XLSX.readFile(xlsxPath);
const ws = wb.Sheets["Model Portfolios"];
if (!ws) throw new Error("Sheet 'Model Portfolios' not found in " + xlsxPath);
const num = (addr) => (ws[addr] && ws[addr].v != null ? Number(ws[addr].v) : null);
const str = (addr) => (ws[addr] && ws[addr].v != null ? String(ws[addr].v).trim() : "");

const models = [];
for (let r = FIRST_ROW; r <= LAST_ROW; r++) {
  const name = str("C" + r);
  if (!name) continue;
  const cpiPlusTarget = round1(num("R" + r) * 100); // stored as fraction in the sheet
  const vol = round1(num("S" + r) * 100);
  const ter = round2(num("Q" + r) * 100);
  const volPeriod = str("T" + r);
  const risk = str("B" + r);
  const nominalReturn = round1(cpiPlusTarget + INFLATION_ASSUMPTION);
  models.push({ key: slug(name), name, risk, cpiPlusTarget, vol, volPeriod, ter, nominalReturn });
}

if (models.length === 0) throw new Error("No models read from " + xlsxPath);

const banner =
  "// AUTO-GENERATED by scripts/sync-models.mjs from the DNA model-portfolio spreadsheet.\n" +
  "// Do NOT edit by hand — run `npm run sync-models` to refresh from data/*.xlsx.\n" +
  "// Source: " + xlsxPath.replace(ROOT, ".").replace(/\\/g, "/") + "\n" +
  "// Generated: " + new Date().toISOString() + "\n";

const body =
  banner +
  "\n" +
  "export interface DnaModel {\n" +
  "  key: string;\n" +
  "  name: string;\n" +
  "  risk: string;\n" +
  "  /** Real return target above CPI, in % p.a. (spreadsheet column R). */\n" +
  "  cpiPlusTarget: number;\n" +
  "  /** Annualised volatility, in % (spreadsheet column S). */\n" +
  "  vol: number;\n" +
  "  /** Basis of the volatility figure, e.g. \"7yr\" (spreadsheet column T). */\n" +
  "  volPeriod: string;\n" +
  "  /** Total expense ratio, in % p.a. (spreadsheet column Q). */\n" +
  "  ter: number;\n" +
  "  /** Nominal expected return = cpiPlusTarget + INFLATION_ASSUMPTION, in % p.a. */\n" +
  "  nominalReturn: number;\n" +
  "}\n\n" +
  "/** Inflation assumption used to derive nominalReturn from the real CPI+ targets. */\n" +
  "export const INFLATION_ASSUMPTION = " + INFLATION_ASSUMPTION + ";\n\n" +
  "export const DNA_MODELS: DnaModel[] = " +
  JSON.stringify(models, null, 2) +
  ";\n";

writeFileSync(outPath, body);
console.log("Wrote " + models.length + " models -> " + outPath);
for (const m of models) {
  console.log(
    "  " + m.name.padEnd(38) +
    " ret " + m.nominalReturn.toFixed(1) + "%  vol " + m.vol.toFixed(1) + "% (" + m.volPeriod + ")"
  );
}

// ---------------------------------------------------------------------------
// Monarch Integrate range — second model-portfolio range, same workbook.
// Sheet layout (header row 6, data rows 7-11):
//   A risk category | B model name | C-K asset classes | L total | M DFM fee
//   | N underlying blended TIC | O total effective cost | P CPI+ target
//   | Q volatility (5yr actual) | R Reg 28 compliant
// ---------------------------------------------------------------------------
const monarchOutPath = join(ROOT, "models", "monarchModels.ts");
const MONARCH_FIRST_ROW = 7;
const MONARCH_LAST_ROW = 11;
const MONARCH_VOL_PERIOD = "5yr"; // fixed for every Monarch model (max available history)

const wsMonarch = wb.Sheets["Monarch Model Portfolios"];
if (!wsMonarch) throw new Error("Sheet 'Monarch Model Portfolios' not found in " + xlsxPath);
const numM = (addr) => (wsMonarch[addr] && wsMonarch[addr].v != null ? Number(wsMonarch[addr].v) : null);
const strM = (addr) => (wsMonarch[addr] && wsMonarch[addr].v != null ? String(wsMonarch[addr].v).trim() : "");

function slugMonarch(name) {
  return name
    .replace(/Monarch/gi, "")
    .replace(/Integrate/gi, "")
    .replace(/Portfolio/gi, "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const monarchModels = [];
for (let r = MONARCH_FIRST_ROW; r <= MONARCH_LAST_ROW; r++) {
  const name = strM("B" + r);
  if (!name) continue;
  const cpiPlusTarget = round1(numM("P" + r) * 100);
  const vol = round2(numM("Q" + r) * 100);
  const totalEffectiveCost = round2(numM("O" + r) * 100);
  const risk = strM("A" + r);
  const reg28 = strM("R" + r) === "Yes";
  const nominalReturn = round1(cpiPlusTarget + INFLATION_ASSUMPTION);
  monarchModels.push({
    key: slugMonarch(name), name, risk, cpiPlusTarget, vol,
    volPeriod: MONARCH_VOL_PERIOD, totalEffectiveCost, nominalReturn, reg28,
  });
}

if (monarchModels.length === 0) throw new Error("No Monarch models read from " + xlsxPath);

const monarchBanner =
  "// AUTO-GENERATED by scripts/sync-models.mjs from the Monarch Integrate model-portfolio sheet.\n" +
  "// Do NOT edit by hand — run `npm run sync-models` to refresh from data/*.xlsx.\n" +
  "// Source: " + xlsxPath.replace(ROOT, ".").replace(/\\/g, "/") + " (sheet: Monarch Model Portfolios)\n" +
  "// Generated: " + new Date().toISOString() + "\n";

const monarchBody =
  monarchBanner +
  "\n" +
  "export interface MonarchModel {\n" +
  "  key: string;\n" +
  "  name: string;\n" +
  "  risk: string;\n" +
  "  /** Real return target above CPI, in % p.a. (spreadsheet column P). Extrapolated for Income/Equity - see sheet notes. */\n" +
  "  cpiPlusTarget: number;\n" +
  "  /** Annualised volatility, in % - actual portfolio 5yr std dev, the max available history (spreadsheet column Q). */\n" +
  "  vol: number;\n" +
  "  /** Basis of the volatility figure - fixed \"5yr\" for every Monarch model. */\n" +
  "  volPeriod: string;\n" +
  "  /** All-in cost, in % p.a.: DFM fee + underlying blended TIC, or the replicated fund-of-funds' own TIC where verified (spreadsheet column O). */\n" +
  "  totalEffectiveCost: number;\n" +
  "  /** Nominal expected return = cpiPlusTarget + INFLATION_ASSUMPTION, in % p.a. */\n" +
  "  nominalReturn: number;\n" +
  "  /** Whether the model is Regulation 28 compliant (spreadsheet column R). */\n" +
  "  reg28: boolean;\n" +
  "}\n\n" +
  "export const MONARCH_MODELS: MonarchModel[] = " +
  JSON.stringify(monarchModels, null, 2) +
  ";\n";

writeFileSync(monarchOutPath, monarchBody);
console.log("\nWrote " + monarchModels.length + " models -> " + monarchOutPath);
for (const m of monarchModels) {
  console.log(
    "  " + m.name.padEnd(38) +
    " ret " + m.nominalReturn.toFixed(1) + "%  vol " + m.vol.toFixed(2) + "% (" + m.volPeriod + ")" +
    "  cost " + m.totalEffectiveCost.toFixed(2) + "%" + (m.reg28 ? "" : "  [Reg28: No]")
  );
}
