// AUTO-GENERATED by scripts/sync-models.mjs from the DNA model-portfolio spreadsheet.
// Do NOT edit by hand — run `npm run sync-models` to refresh from data/*.xlsx.
// Source: ./data/DNA_Model_Portfolio_Metrics_130726.xlsx
// Generated: 2026-07-23T08:15:50.331Z

export interface DnaModel {
  key: string;
  name: string;
  risk: string;
  /** Real return target above CPI, in % p.a. (spreadsheet column R). */
  cpiPlusTarget: number;
  /** Annualised volatility, in % (spreadsheet column S). */
  vol: number;
  /** Basis of the volatility figure, e.g. "7yr" (spreadsheet column T). */
  volPeriod: string;
  /** Total expense ratio, in % p.a. (spreadsheet column Q). */
  ter: number;
  /** Nominal expected return = cpiPlusTarget + INFLATION_ASSUMPTION, in % p.a. */
  nominalReturn: number;
}

/** Inflation assumption used to derive nominalReturn from the real CPI+ targets. */
export const INFLATION_ASSUMPTION = 5;

export const DNA_MODELS: DnaModel[] = [
  {
    "key": "income",
    "name": "DNA Income Portfolio",
    "risk": "Conservative",
    "cpiPlusTarget": 1,
    "vol": 2.1,
    "volPeriod": "7yr",
    "ter": 0.45,
    "nominalReturn": 6
  },
  {
    "key": "moderate-conservative",
    "name": "DNA Moderate Conservative Portfolio",
    "risk": "Moderate Conservative",
    "cpiPlusTarget": 2.5,
    "vol": 7.7,
    "volPeriod": "7yr",
    "ter": 0.66,
    "nominalReturn": 7.5
  },
  {
    "key": "moderate",
    "name": "DNA Moderate Portfolio",
    "risk": "Moderate",
    "cpiPlusTarget": 3.5,
    "vol": 9.4,
    "volPeriod": "7yr",
    "ter": 0.4,
    "nominalReturn": 8.5
  },
  {
    "key": "moderate-aggressive",
    "name": "DNA Moderate Aggressive Portfolio",
    "risk": "Moderate Aggressive",
    "cpiPlusTarget": 5,
    "vol": 10.4,
    "volPeriod": "7yr",
    "ter": 0.69,
    "nominalReturn": 10
  },
  {
    "key": "agressive-equity",
    "name": "DNA Agressive Equity Portfolio",
    "risk": "Aggressive",
    "cpiPlusTarget": 6.5,
    "vol": 11.8,
    "volPeriod": "7yr",
    "ter": 0.37,
    "nominalReturn": 11.5
  },
  {
    "key": "global-aggressive",
    "name": "DNA Global Aggressive Portfolio",
    "risk": "Aggressive",
    "cpiPlusTarget": 7,
    "vol": 12.6,
    "volPeriod": "7yr",
    "ter": 0.43,
    "nominalReturn": 12
  }
];
