// AUTO-GENERATED by scripts/sync-models.mjs from the Monarch Integrate model-portfolio sheet.
// Do NOT edit by hand — run `npm run sync-models` to refresh from data/*.xlsx.
// Source: ./data/DNA_Model_Portfolio_Metrics_130726.xlsx (sheet: Monarch Model Portfolios)
// Generated: 2026-07-24T13:29:27.920Z

export interface MonarchModel {
  key: string;
  name: string;
  risk: string;
  /** Real return target above CPI, in % p.a. (spreadsheet column P). Extrapolated for Income/Equity - see sheet notes. */
  cpiPlusTarget: number;
  /** Annualised volatility, in % - actual portfolio 5yr std dev, the max available history (spreadsheet column Q). */
  vol: number;
  /** Basis of the volatility figure - fixed "5yr" for every Monarch model. */
  volPeriod: string;
  /** All-in cost, in % p.a.: DFM fee + underlying blended TIC, or the replicated fund-of-funds' own TIC where verified (spreadsheet column O). */
  totalEffectiveCost: number;
  /** Nominal expected return = cpiPlusTarget + INFLATION_ASSUMPTION, in % p.a. */
  nominalReturn: number;
  /** Whether the model is Regulation 28 compliant (spreadsheet column R). */
  reg28: boolean;
}

export const MONARCH_MODELS: MonarchModel[] = [
  {
    "key": "income",
    "name": "Monarch Integrate Income Portfolio",
    "risk": "Conservative",
    "cpiPlusTarget": 1,
    "vol": 3.91,
    "volPeriod": "5yr",
    "totalEffectiveCost": 1.48,
    "nominalReturn": 6,
    "reg28": true
  },
  {
    "key": "moderate-conservative",
    "name": "Monarch Integrate Moderate Conservative Portfolio",
    "risk": "Moderately Conservative",
    "cpiPlusTarget": 2.5,
    "vol": 7.63,
    "volPeriod": "5yr",
    "totalEffectiveCost": 1.8,
    "nominalReturn": 7.5,
    "reg28": true
  },
  {
    "key": "moderate",
    "name": "Monarch Integrate Moderate Portfolio",
    "risk": "Moderate",
    "cpiPlusTarget": 3.5,
    "vol": 8.66,
    "volPeriod": "5yr",
    "totalEffectiveCost": 1.96,
    "nominalReturn": 8.5,
    "reg28": true
  },
  {
    "key": "moderate-aggressive",
    "name": "Monarch Integrate Moderate Aggressive Portfolio",
    "risk": "Moderately Aggressive",
    "cpiPlusTarget": 5,
    "vol": 9.59,
    "volPeriod": "5yr",
    "totalEffectiveCost": 2.15,
    "nominalReturn": 10,
    "reg28": true
  },
  {
    "key": "equity",
    "name": "Monarch Integrate Equity Portfolio",
    "risk": "Aggressive",
    "cpiPlusTarget": 6.5,
    "vol": 10.63,
    "volPeriod": "5yr",
    "totalEffectiveCost": 2.49,
    "nominalReturn": 11.5,
    "reg28": false
  }
];
